.dccDropdown_js_metadata <- function() {
deps_metadata <- list(`dcc_dropdown` = structure(list(name = "dcc_dropdown",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DccDropdown.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dccDropdown",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dcc_dropdown` = structure(list(name = "dcc_dropdown",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DccDropdown.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dccDropdown",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dcc_dropdown` = structure(list(name = "dcc_dropdown",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dcc_dropdown.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dccDropdown",
all_files = FALSE), class = "html_dependency"),
`dcc_dropdown` = structure(list(name = "dcc_dropdown",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dcc_dropdown.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dccDropdown",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
